USE WORLD; /* SELECIONA O BANCO WORLD*/
SELECT * FROM CITY; /* SELECIONA A COLUNA CITY DENTRO DO BANCO WORLD E EXIBE */
SELECT * FROM COUNTRY; /* SELECIONA A COLUNA COUNTRY DENTRO DO BANCO WORLD E EXIBE */

CREATE DATABASE SUCOS; /* CRIA O BANCO SUCOS */
DROP DATABASE SUCOS; /* EXCLUI O BANCO SUCOS */